Loading dataset from /scr/Pedram/VisualLearning/processed_bdd100k/train/
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7040/7040 [00:23<00:00, 304.72it/s]
Traceback (most recent call last):
  File "/home/pedram/VisualLearning/TTT-AD/main.py", line 37, in <module>
    train_model(args)
  File "/home/pedram/VisualLearning/TTT-AD/main.py", line 18, in train_model
    loader = DataLoader(dataset, batch_size=32, shuffle=True, device=args.device, num_workers=32)
TypeError: __init__() got an unexpected keyword argument 'device'
Traceback (most recent call last):
  File "/home/pedram/VisualLearning/TTT-AD/main.py", line 37, in <module>
    train_model(args)
  File "/home/pedram/VisualLearning/TTT-AD/main.py", line 18, in train_model
    loader = DataLoader(dataset, batch_size=32, shuffle=True, device=args.device, num_workers=32)
TypeError: __init__() got an unexpected keyword argument 'device'
